name: Build and deploy Flutter Web App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Add web.config for Azure Web Apps
        run: |
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <staticContent>
                <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
              </staticContent>
              <httpProtocol>
                <customHeaders>
                  <add name="Cache-Control" value="no-cache, no-store, must-revalidate" />
                  <add name="Pragma" value="no-cache" />
                  <add name="Expires" value="-1" />
                </customHeaders>
              </httpProtocol>
              <rewrite>
                <rules>
                  <rule name="Flutter Route" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/index.html" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>' > build/web/web.config

      - name: Zip artifact for deployment
        run: zip -r release.zip build/web

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_59907E17074943F78E67430F228727B8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5F33B24B49C42DB87BC5CE673738FBD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54A5CC0CB4444C9798E03FD8DD9097B5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'flutter-webapp-003'
          slot-name: 'Production'
          package: release.zip
